#lang racket/base

(provide menu)

(define (menu)
  `(header ((class "header"))
           (ul ((class "hdr-ul"))
               (li ((class "hdr-li"))
                   (a ((href "/")
                       (class "hdr-a hdr-a1"))
                      "Home")))
           (ul ((class "hdr-ul"))
               (li ((class "hdr-li"))
                   (a ((href "/blog")
                       (class "hdr-a hdr-a2"))
                      "Blog"))
               (li ((class "hdr-li"))
                   (a ((href "#")
                       (class "hdr-a hdr-a3"))
                      "Projects"))
               (li ((class "hdr-li"))
                   (a ((href "#")
                       (class "hdr-a hdr-a4"))
                      "About"))
               (li ((class "hdr-li"))
                   (a ((href "#")
                       (class "hdr-a hdr-a5"))
                      "More")))))