#lang racket

(require web-server/servlet)

(provide sidebar)

(define (sidebar)
  `(div ((class "sidebar"))
        (div ((class "sidebar-content"))
             (a ((href "https://github.com/assefamaru")
                 (target "_blank"))
                (i ((class "fa fa-github")
                    (area-hidden "true"))))
             (a ((href "https://www.linkedin.com/in/alexandermaru")
                 (target "_blank"))
                (i ((class "fa fa-linkedin")
                    (area-hidden "true"))))
             (a ((href "https://twitter.com/assefamaru")
                 (target "_blank"))
                (i ((class "fa fa-twitter")
                    (area-hidden "true"))))
             (a ((href "https://stackoverflow.com/users/4739247/assefamaru")
                 (target "_blank"))
                (i ((class "fa fa-stack-overflow")
                    (area-hidden "true"))))
             (a ((href "https://www.instagram.com/assefamaru")
                 (target "_blank"))
                (i ((class "fa fa-instagram")
                    (area-hidden "true")))))))