#lang racket/base

(provide sidebar sidebar-right)

(define (sidebar)
  `(div ((class "sidebar"))
        (div ((class "sidebar-content"))
             (a ((href "https://github.com/assefamaru")
                 (target "_blank"))
                (i ((class "fa fa-github")
                    (area-hidden "true"))))
             (a ((href "https://www.linkedin.com/in/alexandermaru")
                 (target "_blank"))
                (i ((class "fa fa-linkedin")
                    (area-hidden "true"))))
             (a ((href "https://twitter.com/assefamaru")
                 (target "_blank"))
                (i ((class "fa fa-twitter")
                    (area-hidden "true"))))
             (a ((href "https://stackoverflow.com/users/4739247/assefamaru")
                 (target "_blank"))
                (i ((class "fa fa-stack-overflow")
                    (area-hidden "true"))))
             (a ((href "https://www.instagram.com/assefamaru")
                 (target "_blank"))
                (i ((class "fa fa-instagram")
                    (area-hidden "true")))))))

(define (sidebar-right)
  `(div ((class "sidebar sidebar-right"))
        (div ((class "sidebar-right-content"))
             (a ((href "/login"))
                (i ((class "fa fa-lock")
                    (area-hidden "true"))))
             (a ((href "#"))
                (i ((class "fa fa-adjust")
                    (area-hidden "true")))))))